// Generated by dts-bundle-generator v9.5.1

import { BundledLanguage, BundledTheme, CodeToHastOptions } from 'shiki';
import { Action } from 'svelte/action';

/**
 * Svelte action to enable copy button functionality for mdsvex-shiki code blocks.
 * Apply this action to a container element that contains the code blocks.
 *
 * @example
 * ```svelte
 * <div use:copyAction>
 *   {@html content}
 * </div>
 * ```
 */
export declare const copyAction: Action<HTMLElement>;
export type HighlighterOptions = {
	displayTitle?: boolean;
	displayLanguage?: boolean;
	disableCopyButton?: boolean;
	shikiOptions?: Partial<CodeToHastOptions<BundledLanguage, BundledTheme>> & {
		themes?: BundledTheme[] | {
			light: BundledTheme;
			dark: BundledTheme;
		} | BundledTheme;
		langs?: BundledLanguage[] | "all";
	};
};
export declare const defaultShikiOptions: Partial<CodeToHastOptions<BundledLanguage, BundledTheme>>;
export declare const mdsvexShiki: (config: HighlighterOptions) => Promise<(code: string, lang: string) => Promise<string>>;

export {
	mdsvexShiki as default,
};

export {};
